// Frontend/list12/todo-list-svelte/src/components/TodoList.svelte
<script lang="ts">
  import TodoItem from "./TodoItem.svelte";
  import type { Todo } from "../types";

  export let todos: Todo[];
  export let onToggle: (id: number) => void;
  export let onRemove: (id: number) => void;
  export let onMoveUp: (id: number) => void;
  export let onMoveDown: (id: number) => void;
</script>

<ul class="todos__list">
  {#each todos as todo, idx}
    <TodoItem
      {todo}
      index={idx}
      total={todos.length}
      onToggle={onToggle}
      onRemove={onRemove}
      onMoveUp={onMoveUp}
      onMoveDown={onMoveDown}
    />
  {/each}
</ul>

// Frontend/list11/todo-app/src/components/TodoList.tsx
import type { Todo } from "../types";
import { TodoItem } from "./TodoItem";

type Props = {
  todos: Todo[];
  onToggle: (id: number) => void;
  onRemove: (id: number) => void;
  onMoveUp: (id: number) => void;
  onMoveDown: (id: number) => void;
};

export const TodoList: React.FC<Props> = ({
  todos,
  onToggle,
  onRemove,
  onMoveUp,
  onMoveDown,
}) => {
  return (
    <ul id="todo-list" className="todos__list">
      {todos.map((todo, idx) => (
        <TodoItem
          key={todo.id}
          todo={todo}
          index={idx}
          total={todos.length}
          onToggle={onToggle}
          onRemove={onRemove}
          onMoveUp={onMoveUp}
          onMoveDown={onMoveDown}
        />
      ))}
    </ul>
  );
};
