// Frontend/list12/todo-list-svelte/src/components/todoForm.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher();
  let text = "";

  function handleSubmit(e: Event) {
    e.preventDefault();
    if (text.trim()) {
      dispatch("add", text.trim());
      text = "";
    }
  }
</script>

<form class="add-item__container" on:submit={handleSubmit}>
  <input
    type="text"
    placeholder="What's on your mind?"
    class="add-item__element add-item__input"
    bind:value={text}
    required
  />
  <button type="submit" class="add-item__element add-item__submit">Add</button>
</form>

// Frontend/list11/todo-app/src/components/TodoForm.tsx
import { useState } from "react";

type Props = {
  onAdd: (text: string) => void;
};

export const TodoForm: React.FC<Props> = ({ onAdd }) => {
  const [value, setValue] = useState("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!value.trim()) return;
    onAdd(value.trim());
    setValue("");
  };

  return (
    <form className="add-item__container" onSubmit={handleSubmit}>
      <input
        type="text"
        name="todo-name"
        className="add-item__element add-item__input"
        placeholder="What's on your mind?"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        required
      />
      <button type="submit" className="add-item__element add-item__submit">
        Add
      </button>
    </form>
  );
};
